// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6TyHsL6LyALyFVVupC7oeX9UcTCsrOfo',
    appId: '1:555755108862:web:4df2c7f3cc42cc2d5168af',
    messagingSenderId: '555755108862',
    projectId: 'catalog-digitization-ebc51',
    authDomain: 'catalog-digitization-ebc51.firebaseapp.com',
    storageBucket: 'catalog-digitization-ebc51.appspot.com',
    measurementId: 'G-5TRRFHQLQY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaqQyiMTmDqbObvJwZfbh0hjXMT4-Qw6s',
    appId: '1:555755108862:android:1d72cc5edfe5cf355168af',
    messagingSenderId: '555755108862',
    projectId: 'catalog-digitization-ebc51',
    storageBucket: 'catalog-digitization-ebc51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3hQ41CM2zhLVsS076K-_gtQLAShkjFDs',
    appId: '1:555755108862:ios:b52dfab6cc5fd3c05168af',
    messagingSenderId: '555755108862',
    projectId: 'catalog-digitization-ebc51',
    storageBucket: 'catalog-digitization-ebc51.appspot.com',
    iosBundleId: 'com.example.catalogDigitizationOndc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3hQ41CM2zhLVsS076K-_gtQLAShkjFDs',
    appId: '1:555755108862:ios:47a070b5df0e7c7e5168af',
    messagingSenderId: '555755108862',
    projectId: 'catalog-digitization-ebc51',
    storageBucket: 'catalog-digitization-ebc51.appspot.com',
    iosBundleId: 'com.example.catalogDigitizationOndc.RunnerTests',
  );
}
